### PR TITLE
add config file and support multiplatform -fuch u 

### PR DESCRIPTION
**Pull request by Mazafard**
change fucking code to multi-platform and add config file.
before leaving home, please meet me on downstairs. ( 👍 )

### CODE REVIEW

**Comment by meysampg** [comment]
There's a little inconsistency in your modifications with the philosophy of this project. Each utility on this package must be small and in a directory named with the tool's name. For example suppose this package has two tools named `ls` and `pwd`. The structure of project must be like this:

```
src
  -| ls
   -- ls.go (contains main package of `ls`) 
   -- another_file.go
   -- and_so_on.go
  -| pwd
   -- pwd.go (contains main package of `pwd`)
   -- another_file.go
```

Can you fix this issue?

P.S. Thanks for the morning Pizza! :heart:

**Comment by Mazafard** [comment]
There is no difficulty. i fixed this shit.
please check agian and let me know.
noshe jon bro! 💟 
please buy some **[bread](http://nonba.ir)** whenever want to come back home. 🌮

**Comment by meysampg** [comment]
Hey man I think the `app` folder is redundant! All of this small tools are an app and their folders must be on the root of `src` (based on https://github.com/meysampg/mpgutils/pull/1#issuecomment-284941100). Do you have another idea?

Ps. OK! I think it's a good idea to make an omlet for the launch, so I gonna buy eggs on comeback.

**Comment by Mazafard** [comment]
dude! 
I’m not exactly sure, but let's read gb's [document](https://getgb.io/examples/getting-started/) about structure of that:

> A gb project is defined as any directory that has a src/ subdirectory. <br>

as we know, the structure of project that used gb, must be like this:
```.
└── src 
     └── cmd
          └── helloworld
```
I suggest break your mental framework and continue to build productive app, So, You know...

***
Shit I heard that! Let's roll.

**Comment by meysampg** [comment]
Thanks Mazafard! :+1:

**Pull request merged**
